name       : qt6-networkauth
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtnetworkauth-everywhere-src-6.2.2.tar.xz : c8217c740167b9e96c3fabcc92d781864220c553c7a23254c16bd8f09f05e9e1
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 NetworkAuth components
description: |
    Qt Network Authorization provides a set of APIs that enable Qt applications to obtain limited access to online accounts and HTTP services without exposing users' passwords.
builddeps  :
    - pkgconfig(Qt6Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
